#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Sun Apr 10 00:30:04 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.BORDER_NONE
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_button_1 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("3DPrince.bmp", wx.BITMAP_TYPE_ANY))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Makerbot2"))
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("1800"), style=wx.ALIGN_RIGHT)
        self.bitmap_button_2 = wx.BitmapButton(self, wx.ID_ANY, wx.Bitmap("Settings.bmp", wx.BITMAP_TYPE_ANY))
        self.static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.static_line_2 = wx.StaticLine(self, wx.ID_ANY)
        self.static_line_3 = wx.StaticLine(self, wx.ID_ANY)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Category"))
        self.list_box_1 = wx.ListBox(self, wx.ID_ANY, choices=[_("choice 1")], style=wx.LB_NEEDED_SB | wx.LB_SORT)
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Items"))
        self.list_box_2 = wx.ListBox(self, wx.ID_ANY, choices=[_("choice 1"), _("New"), _("List"), _("Item")], style=wx.LB_NEEDED_SB)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClickLogo, self.bitmap_button_1)
        self.Bind(wx.EVT_BUTTON, self.OnClickPrinter, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.OnClickSettings, self.bitmap_button_2)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnClickCategoy, self.list_box_1)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnClickItem, self.list_box_2)
        # end wxGlade
        self.Bind(wx.EVT_KEY_UP, self.OnKeyUP)

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((320, 240))
        self.SetBackgroundColour(wx.Colour(153, 153, 255))
        self.bitmap_button_1.SetMinSize((50, 50))
        self.button_2.SetMinSize((90, 30))
        self.button_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_3.SetMinSize((90, 25))
        self.label_3.SetBackgroundColour(wx.Colour(153, 153, 255))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.bitmap_button_2.SetMinSize((50, 50))
        self.bitmap_button_2.SetBackgroundColour(wx.Colour(153, 153, 255))
        self.label_1.SetBackgroundColour(wx.Colour(153, 153, 255))
        self.label_1.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, ""))
        self.list_box_1.SetMinSize((145, 150))
        self.list_box_1.SetSelection(0)
        self.label_2.SetBackgroundColour(wx.Colour(153, 153, 255))
        self.label_2.SetFont(wx.Font(12, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Copperplate Gothic Light"))
        self.list_box_2.SetMinSize((145, 150))
        self.list_box_2.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.bitmap_button_1, 0, wx.LEFT | wx.TOP, 5)
        sizer_2.Add(self.button_2, 0, wx.TOP, 5)
        grid_sizer_1.Add(sizer_2, 1, 0, 0)
        grid_sizer_1.Add((10, 20), 0, 0, 0)
        sizer_4.Add(self.label_3, 0, wx.BOTTOM | wx.TOP, 15)
        sizer_4.Add(self.bitmap_button_2, 0, wx.TOP, 2)
        grid_sizer_1.Add(sizer_4, 1, 0, 0)
        grid_sizer_1.Add(self.static_line_1, 0, wx.EXPAND | wx.TOP, 2)
        grid_sizer_1.Add(self.static_line_2, 0, wx.EXPAND | wx.TOP, 2)
        grid_sizer_1.Add(self.static_line_3, 0, wx.EXPAND | wx.TOP, 2)
        sizer_3.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_3.Add(self.list_box_1, 0, wx.ALL, 5)
        grid_sizer_1.Add(sizer_3, 1, 0, 0)
        grid_sizer_1.Add((10, 200), 0, 0, 0)
        sizer_5.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(self.list_box_2, 0, wx.ALL, 3)
        grid_sizer_1.Add(sizer_5, 1, 0, 0)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade
        
    def OnKeyUP(self, event):
        keyCode = event.GetKeyCode()
        if keyCode == wx.WXK_ESCAPE:
            print 'closing'
            self.Close()
        
    def OnClickLogo(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnClickLogo' not implemented!"
        LogoPop = LogoDialog(self)
        LogoPop.ShowModal()
        LogoPop.Destroy()
        event.Skip()
    def OnClickPrinter(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnClickPrinter' not implemented!"
        PrinterPop = PrinterDialog(self)
        PrinterPop.ShowModal()
        PrinterPop.Destroy()
        event.Skip()        
        event.Skip()

    def OnClickSettings(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnClickSettings' not implemented!"
        SettingPop = SettingDialog(self)
        SettingPop.ShowModal()
        SettingPop.Destroy()
        event.Skip()
        event.Skip()

    def OnClickCategoy(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnClickCategoy' not implemented!"
        event.Skip()

    def OnClickItem(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'OnClickItem' not implemented!"
        ItemPop = ItemDialog(self)
        ItemPop.ShowModal()
        ItemPop.Destroy()
        event.Skip()        
        event.Skip()

# end of class MyFrame

class SettingDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingDialog.__init__
        kwds["style"] = wx.MINIMIZE_BOX
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("Hotend Temperature"))
        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "195", min=0, max=300)
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("Bed Temperature"))
        self.spin_ctrl_2 = wx.SpinCtrl(self, wx.ID_ANY, "60", min=0, max=140)
        self.button_7 = wx.Button(self, wx.ID_CANCEL, "")
        self.button_1 = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_SPINCTRL, self.HotendTemp, self.spin_ctrl_1)
        self.Bind(wx.EVT_SPINCTRL, self.BedTemp, self.spin_ctrl_2)
        self.Bind(wx.EVT_BUTTON, self.OnClickCancel, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.OnClickPrinterOK, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SettingDialog.__set_properties
        self.SetTitle(_("dialog_1"))
        self.SetSize((222, 130))
        self.spin_ctrl_1.SetMinSize((60, 25))
        self.spin_ctrl_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.spin_ctrl_2.SetMinSize((60, 25))
        self.spin_ctrl_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.button_7.SetMinSize((70, 25))
        self.button_1.SetMinSize((70, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SettingDialog.__do_layout
        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 10)
        grid_sizer_2.Add(self.spin_ctrl_1, 0, wx.ALIGN_RIGHT | wx.TOP, 10)
        grid_sizer_2.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT, 10)
        grid_sizer_2.Add(self.spin_ctrl_2, 0, wx.ALIGN_RIGHT | wx.BOTTOM, 10)
        grid_sizer_2.Add(self.button_7, 0, wx.LEFT, 40)
        grid_sizer_2.Add(self.button_1, 0, wx.LEFT, 10)
        self.SetSizer(grid_sizer_2)
        self.Layout()
        # end wxGlade

    def HotendTemp(self, event):  # wxGlade: SettingDialog.<event_handler>
        print "Event handler 'HotendTemp' not implemented!"
        event.Skip()

    def BedTemp(self, event):  # wxGlade: SettingDialog.<event_handler>
        print "Event handler 'BedTemp' not implemented!"
        event.Skip()

    def OnClickCancel(self, event):  # wxGlade: SettingDialog.<event_handler>
        print "Event handler 'OnClickCancel' not implemented!"
        event.Skip()

    def OnClickPrinterOK(self, event):  # wxGlade: SettingDialog.<event_handler>
        print "Event handler 'OnClickPrinterOK' not implemented!"
        event.Skip()

# end of class SettingDialog

class PrinterDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PrinterDialog.__init__
        kwds["style"] = wx.MINIMIZE_BOX
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_6 = wx.StaticText(self, wx.ID_ANY, _("Select your 3D printer"), style=wx.ALIGN_CENTER)
        self.list_box_3 = wx.ListBox(self, wx.ID_ANY, choices=[_("choice 1")], style=wx.LB_NEEDED_SB)
        self.button_5 = wx.Button(self, wx.ID_CANCEL, "")
        self.button_3 = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnClickPrinter, self.list_box_3)
        self.Bind(wx.EVT_BUTTON, self.OnClickCancel, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.OnClickOK, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PrinterDialog.__set_properties
        self.SetTitle(_("dialog_2"))
        self.SetSize((250, 201))
        self.label_6.SetMinSize((190, 19))
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.list_box_3.SetMinSize((160, 130))
        self.list_box_3.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PrinterDialog.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.label_6, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.TOP, 7)
        sizer_6.Add(self.list_box_3, 0, wx.ALIGN_CENTER | wx.BOTTOM, 5)
        sizer_7.Add(self.button_5, 0, wx.LEFT | wx.RIGHT, 30)
        sizer_7.Add(self.button_3, 0, 0, 0)
        sizer_6.Add(sizer_7, 1, 0, 0)
        self.SetSizer(sizer_6)
        self.Layout()
        # end wxGlade

    def OnClickPrinter(self, event):  # wxGlade: PrinterDialog.<event_handler>
        print "Event handler 'OnClickPrinter' not implemented!"
        event.Skip()

    def OnClickCancel(self, event):  # wxGlade: PrinterDialog.<event_handler>
        print "Event handler 'OnClickCancel' not implemented!"
        event.Skip()

    def OnClickOK(self, event):  # wxGlade: PrinterDialog.<event_handler>
        print "Event handler 'OnClickOK' not implemented!"
        event.Skip()

# end of class PrinterDialog

class ItemDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ItemDialog.__init__
        kwds["style"] = wx.MINIMIZE_BOX
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("Bitmap.bmp", wx.BITMAP_TYPE_ANY))
        self.label_7 = wx.StaticText(self, wx.ID_ANY, _("Start printing item?"))
        self.button_6 = wx.Button(self, wx.ID_CANCEL, "")
        self.button_4 = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClickCancel, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.OnClickItemOK, self.button_4)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ItemDialog.__set_properties
        self.SetTitle(_("dialog_3"))
        self.SetSize((250, 180))
        self.bitmap_1.SetMinSize((190, 100))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ItemDialog.__do_layout
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(self.bitmap_1, 0, wx.ALIGN_CENTER, 0)
        sizer_8.Add(self.label_7, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.TOP, 6)
        sizer_9.Add(self.button_6, 0, wx.LEFT | wx.RIGHT, 30)
        sizer_9.Add(self.button_4, 0, 0, 0)
        sizer_8.Add(sizer_9, 1, 0, 0)
        self.SetSizer(sizer_8)
        self.Layout()
        # end wxGlade

    def OnClickCancel(self, event):  # wxGlade: ItemDialog.<event_handler>
        print "Event handler 'OnClickCancel' not implemented!"
        event.Skip()

    def OnClickItemOK(self, event):  # wxGlade: ItemDialog.<event_handler>
        print "Event handler 'OnClickItemOK' not implemented!"
        event.Skip()

# end of class ItemDialog

class LogoDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LogoDialog.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("Bitmap.bmp", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LogoDialog.__set_properties
        self.SetTitle(_("dialog_4"))
        self.SetSize((250, 150))
        self.bitmap_2.SetMinSize((250, 150))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LogoDialog.__do_layout
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10.Add(self.bitmap_2, 0, 0, 0)
        self.SetSizer(sizer_10)
        self.Layout()
        # end wxGlade

# end of class LogoDialog
# end of class LogoDialog
class MyApp(wx.App):
    def OnInit(self):
        frame_1 = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
    